### ISSUE TITLE
Example of a transfer from scratch

### ISSUE THREAD

**Issue by sebscholl** [AlmostEfficient/transaction-deep-dive#1]
Hey @AlmostEfficient - I really appreciated your YouTube video on this and thanks for sharing the code.

Is there any chance you'd be open to sharing an example of this for a transfer as opposed to Memo? Please let me know and happy to send you a tip if so!

**Comment by AlmostEfficient** [comment]
yo ty,

will try to get this out this week, working on blinks vid rn

**Comment by sebscholl** [comment]
Awesome. Thanks!

**Comment by AlmostEfficient** [comment]
Added in 388d8c0cd969c2ebfe2fe26d154e23056aeba4e7

also take a look at web3.js 

raza.sol :)
